CREATE TABLE [dbo].[Sys_TableList] (
    [Id]                    INT            IDENTITY (1, 1) NOT NULL,
    [CreateDateTime]        DATETIME2 (7)  NOT NULL,
    [DefaultFilter]         NVARCHAR (MAX) NULL,
    [DefaultSort]           NVARCHAR (MAX) NULL,
    [DeleteTableName]       NVARCHAR (MAX) NULL,
    [Description]           NVARCHAR (MAX) NULL,
    [ExtendFunction]        NVARCHAR (MAX) NULL,
    [ForbiddenAddFilter]    NVARCHAR (MAX) NULL,
    [ForbiddenDeleteFilter] NVARCHAR (MAX) NULL,
    [ForbiddenUpdateFilter] NVARCHAR (MAX) NULL,
    [ImportType]            TINYINT        NOT NULL,
    [IsView]                TINYINT        NOT NULL,
    [Name]                  NVARCHAR (MAX) NULL,
    [AllowDelete]           TINYINT        CONSTRAINT [DF__Sys_Table__Allow__3A4CA8FD] DEFAULT ((0)) NOT NULL,
    [AllowEdit]             TINYINT        CONSTRAINT [DF__Sys_Table__Allow__3B40CD36] DEFAULT ((0)) NOT NULL,
    [AllowExport]           TINYINT        CONSTRAINT [DF__Sys_Table__Allow__3C34F16F] DEFAULT ((0)) NOT NULL,
    [AllowImport]           TINYINT        CONSTRAINT [DF__Sys_Table__Allow__3D2915A8] DEFAULT ((0)) NOT NULL,
    [AllowView]             TINYINT        CONSTRAINT [DF__Sys_Table__Allow__3E1D39E1] DEFAULT ((0)) NOT NULL,
    [AllowAdd]              TINYINT        CONSTRAINT [DF__Sys_Table__Allow__3F115E1A] DEFAULT ((0)) NOT NULL,
    [AllowDetail]           TINYINT        CONSTRAINT [DF_Sys_TableList_AllowEdit1] DEFAULT ((0)) NOT NULL,
    [TopExtendFunction]     NVARCHAR (MAX) NULL,
    [ColumnPerRow]          INT            CONSTRAINT [DF__Sys_Table__Colum__756D6ECB] DEFAULT ((0)) NOT NULL,
    [ViewEditWidthHeight]   NVARCHAR (MAX) NULL,
    [ListPageJavaScript]    NVARCHAR (MAX) NULL,
    [AddPageJavaScript]     NVARCHAR (MAX) NULL,
    [EditPageJavaScript]    NVARCHAR (MAX) NULL,
    [DetailPageJavaScript]  NVARCHAR (MAX) NULL,
    [ListPageCssStyle]      NVARCHAR (MAX) NULL,
    [AddPageCssStyle]       NVARCHAR (MAX) NULL,
    [EditPageCssStyle]      NVARCHAR (MAX) NULL,
    [DetailPageCssStyle]    NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Sys_TableList] PRIMARY KEY CLUSTERED ([Id] ASC)
);

